const ActionType = {
    SET_AUTH_USER: 'SET_AUTH_USER',
    UNSET_AUTH_USER: 'UNSET_AUTH_USER',
    SET_IS_PRELOAD: 'SET_IS_PRELOAD',
    REGISTER_USER: 'REGISTER_USER',
    ADD_NOTE: 'ADD_NOTE',
    DELETE_NOTE: 'DELETE_NOTE',
    GET_NOTE: 'GET_NOTE',
    GET_ACTIVE_NOTES: 'GET_ACTIVE_NOTES',
    GET_ARCHIVED_NOTES: 'GET_ARCHIVED_NOTES',
    ARCHIVE_NOTE: 'ARCHIVE_NOTE',
    UNARCHIVE_NOTE: 'UNARCHIVE_NOTE',
};

export default ActionType;
